### PR TITLE
Correct capitalization of Jetpack

### PR DESCRIPTION
**Pull request by georgestephanis**

### CODE REVIEW

**Comment by dovy** [comment]
My bad.  ;)

**Comment by dovy** [comment]
So why can't this go into the core?  :P

**Comment by georgestephanis** [comment]
Core of what?

**Comment by dovy** [comment]
WordPress core as a validation function for CSS.  ;)

**Comment by georgestephanis** [comment]
@nacin actually left a comment on that here: https://make.wordpress.org/themes/2015/02/03/theme-review-chat-notes/#comment-40882

**Comment by dovy** [comment]
Yea, I just don't fully agree. If it's a requirement of WP security it's a WP function, not just something that can exist in plugins since plugins and themes are in separate worlds. I think that thought process is a little odd since it's all the same code base. ;)

**Comment by kprovance** [comment]
Justin said:  "That’s definitely a step forward." in regard to our having to shore up our product, to make up for WP's shortcomings.  Again.  A true step forward would be - as pointed out - WP taking responsibility for their own security.  I think we had a discussion on a certain WP FB group about the problems of 'inward thinking' on the part of the WP dev team.  Case made.

**Pull request merged**
